export { clipDuration, clipEndTime, projectDuration } from "~/core/project/duration";
export {
  type AudioClipOptions,
  type ImageClipOptions,
  type ProjectOptions,
  type VideoClipOptions,
  createAudioAsset,
  createAudioClip,
  createCrop,
  createImageAsset,
  createImageClip,
  createProject,
  createResolution,
  createTrack,
  createTransform,
  createUniformScale,
  createVideoAsset,
  createVideoClip,
} from "~/core/project/factory";
export type {
  Asset,
  AssetMetadata,
  AssetSource,
  AudioClip,
  Clip,
  Crop,
  ExportSettings,
  ImageClip,
  Position,
  Project,
  Resolution,
  Scale,
  Track,
  Transform,
  VideoClip,
} from "~/core/project/types";
